### ISSUE TITLE
Game Saves

### ISSUE THREAD

**Issue by OdroidNoob** [retro-esp32/Retro-Odroid-Go-Firmware#2]
I think it would be a cool idea to have multiple game save slots, such as maybe three which can be access by going to the menu and either pressing savegame / overwrite game and reload game.
I also think when the console is switched off it should save to the last slot opened in the game.

**Comment by 32teeth** [comment]
Can you post this in the [Restro ESP32](https://github.com/retro-esp32/RetroESP32) Launcher Repo
We can Address it there
