### ISSUE TITLE
Screen Flipped Sideways

### ISSUE THREAD

**Issue by NebulaBC** [retro-esp32/Retro-Odroid-Go-Firmware#7]
**Describe the bug**
I am having Issues With my screen orientation. I know this repo has been inactive for a while, but I thought I would at least throw this down in the case anyone sees it.

**To Reproduce**
1. Clone repo
2. go into Firmware/build folder
3. flash with the command `sudo esptool.py write_flash --flash_freq 80m 0xd000 ota_data_initial.bin 0x1000 bootloader/bootloader.bin 0xf000 phy_init_data.bin 0x8000 partitions.bin 0x10000 Retro-Odroid-Go.bin`
4. Boot up
5. Screen is flipped sideways in bootloader. (The picture on the screen is rotated 90 degrees)

**Expected behavior**
Bootloader should run as expected

**Screenshots**
 ![IMG_1941](https://user-images.githubusercontent.com/49570924/144727298-131ddebe-aeca-46d0-ab04-ecf930a18e34.jpg)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu Based (although I plan on trying the flash with my Gentoo or OpenBSD install too)

**Smartphone (please complete the following information):**
 - Device: Odroid Go Hardkernel (ESP32-D0WD (revision 1))

**Comment by 32teeth** [comment]
# easy fix

run `make menuconfig`
go to `retro esp32 options`
select the correct display `Odroid Go - 2.4"`

`make -j16`

**Comment by NebulaBC** [comment]
I remember being able to build this at one point, but now it does not cooperate if I do not clone the esp-idf directory from its github. That's fine (besides having newer versions than expected), but I keep getting stopped at the error `No rule to make target '/Users/andrueu/Desktop/github/RetroESP32/Public/Master/Tools/esp-idf/components/log/log.c', needed by 'log.o'.` I tried looking through my makefile, and can not find where it calls for this. I am a novice at makefiles, but nevertheless I am still stumped at where I can fix this, and set it to my log.c directory.

**Comment by 32teeth** [comment]
you need to run
```
cd scripts
source helpers/paths
```
go back to the firmware directory
```
make clean
```
